// An almost 1:1 recreation of the UT HUD, uses player color for tinting
Class UTHud : BaseStatusBar
{
	override void Init()
	{
		Super.Init();
		SetSize(0,1280,960);
	}

	override void Draw( int state, double TicFrac )
	{
		Super.Draw(state,TicFrac);
		if ( (state == HUD_StatusBar) || (state == HUD_Fullscreen) )
		{
			BeginHUD();
			DrawUTHUD(TicFrac);
		}
	}

	private void DrawUTHUD( double TicFrac )
	{
	}
}
